import Navbar from '../navbar/Navbar';
import React from 'react';
import Head from "next/head";
import Footer from '../footer/Footer';
function Layout({children}) {
    return (
        <div>   
            <Head>
                <title>Next Travel</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar/>
                {children}
            <Footer/>
        </div>
    )
}

export default Layout
