export const GET_TRIP = "GET_TRIP";
export const GET_TRIP_SUCCESS = "GET_TRIP_SUCCESS";
export const GET_TRIP_FAILED = "GET_TRIP_FAILED";

export const READ_ONE_TRIP = "READ_ONE_TRIP";
export const READ_ONE_TRIP_SUCCESS = "READ_ONE_TRIP_SUCCESS";
export const READ_ONE_TRIP_FAILED = "READ_ONE_TRIP_FAILED";


export const CREATE_TRIP = "CREATE_TRIP"
export const CREATE_TRIP_SUCCESS = "CREATE_TRIP_SUCCESS"
export const CREATE_TRIP_FAILED = "CREATE_TRIP_FAILED"

export const EDIT_TRIP = "EDIT_TRIP"
export const EDIT_TRIP_SUCCESS = "EDIT_TRIP_SUCCESS"
export const EDIT_TRIP_FAILED = "EDIT_TRIP_FAILED"

export const DELETE_TRIP = "DELETE_TRIP"
export const DELETE_TRIP_SUCCESS = "DELETE_TRIP_SUCCESS"
export const DELETE_TRIP_FAILED = "DELETE_TRIP_FAILED"

