
export const LOGIN_USER = "LOGIN_USER"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILED = "LOGIN_FAILED"

export const LOGOUT_USER = "LOGOUT_USER"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export const LOGOUT_FAILED = "LOGOUT_FAILED"

export const REGISTER_USER = "REGISTER_USER"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAILED = "REGISTER_FAILED"

export const GET_USER_DATA = "GET_USER_DATA"

export const UPDATE_USER_DATA = "UPDATE_USER_DATA"
export const UPDATE_USER_DATA_SUCCESS = "UPDATE_USER_DATA_SUCCESS"
export const UPDATE_USER_DATA_FAILED = "UPDATE_USER_DATA_FAILED"
export const UPDATE_USER_DATA_RESET = "UPDATE_USER_DATA_RESET"

export const FETCH_USER = "FETCH_USER_DATA"
export const FETCH_USER_SUCCESS = "FETCH_USER_DATA_SUCCESS"
export const FETCH_USER_FAILED = "FETCH_USER_DATA_FAILED"
export const FETCH_USER_RESET = "FETCH_USER_DATA_RESET"

export const USER_IS_UNAUTHORIZED = "USER_IS_UNAUTHORIZED"
export const SET_TOKEN = "SET_TOKEN"